#import "../template/layout-template.typ" as layout
#show: doc => layout.MainPageSettings(doc)

#heading(level: 1, outlined: false)[Abstract]

The rapid digitisation of Tabletop Role-Playing Games (TTRPGs) has introduced complex automation into traditional face-to-face play, creating hybrid "phygital" gaming environments. While digital assistance tools reduce the mathematical and administrative burdens associated with gameplay, their integration into physical spaces risks fracturing social presence and narrative immersion through isolating, "head-down" interaction paradigms. This dissertation investigates whether digital assistance tools deepen or disrupt immersion in in-person TTRPG sessions by altering players' cognitive load.

To explore this, a bespoke, dual-display software artefact was developed using the Unity Engine. Designed through the lens of Cognitive Load Theory, the tool features a private Game Master dashboard for automating spatial measurements and token management, alongside a shared player-facing screen intended to centralise visual attention. The system was evaluated through a mixed-methods user study, triangulating quantitative workload data from the NASA Task Load Index (NASA-TLX) with qualitative thematic analysis of semi-structured player interviews.

The findings indicate that the digital artefact successfully eradicated extraneous cognitive load, evidenced by exceptionally low Frustration (2.6/10) and high Performance (8.8/10) scores, allowing players to redirect their mental effort toward germane, strategic role-play. Furthermore, the shared display fostered "head-up" social dynamics, significantly deepening systemic and imaginative immersion during combat downtime. However, the study also identified a paradox of the hybrid space: while the software protected narrative flow, the physical hardware invited external digital distractions. Ultimately, this research concludes that digital assistance effectively enhances the tabletop experience when designed to centralise shared attention, offering critical UI/UX design guidelines for the future development of hybrid TTRPG software.
